### ISSUE TITLE
anaconda environment not correctly activated on cluster nodes

### ISSUE THREAD

**Issue by jeremymanning** [ContextLab/cluster-tools-dartmouth#1]
what's the right way to do this?

**Comment by KirstensGitHub** [comment]
didn't @jakerost do this successfully?

**Comment by jeremymanning** [comment]
the error i'm getting is that on the head node (the one we ssh into to submit jobs, interact with data, run test scripts, etc.), i can run "source activate <my_virtual_environment>" and then all of the modules that i've installed (e.g. the brain dynamics model) are available.  it seems like on the compute nodes (the ones that actually run the jobs), even though i'm pretty sure they share a filesystem, the installed modules don't seem to be available.

**Comment by paxtonfitzpatrick** [comment]
`module load xxx` and `<source/conda> activate yyy` need to be explicitly called in bash scripts.  Has been fixed
